#!/sbin/openrc-run

name="ssh-honeypotd"
command="/usr/sbin/${name}"
pidfile="/run/${name}/${name}.pid"

: ${DAEMON_USER:=nobody}
: ${DAEMON_GROUP:=nobody}

command_args="${DAEMON_ARGS} -u ${DAEMON_USER} -g ${DAEMON_GROUP} -P ${pidfile}"

depend() {
    need net
    after firewall
}

start_pre() {
    ebegin
    checkpath --directory --owner "root:${DAEMON_GROUP}" "${pidfile%/*}"
    if [ "${ENABLED}" = "0" ]; then
        echo "${name}: disabled, see /etc/conf.d/${name}"
        eend 1;
    fi

    eend $?
}
